import type { Metadata } from 'next'

import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import DashboardIcon from '@mui/icons-material/Dashboard';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

const DRAWER_WIDTH = 240;

import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';

export const metadata: Metadata = {
  title: 'Бложиг о всяких играх',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body>
      <ThemeRegistry>
        <AppBar position="fixed" sx={{ zIndex: 2000 }}>
          <Toolbar sx={{ backgroundColor: 'background.paper' }}>
            <DashboardIcon sx={{ color: '#444', mr: 2, transform: 'translateY(-2px)' }} />
            <Typography variant="h6" color="text.primary">
              Next.js App Router
            </Typography>
          </Toolbar>
        </AppBar>
        <Box
            component="main"
            sx={{
              flexGrow: 1,
              bgcolor: 'background.default',
              ml: `${DRAWER_WIDTH}px`,
              mt: ['48px', '56px', '64px'],
              p: 3,
            }}
        >
          {children}
        </Box>
      </ThemeRegistry>
      </body>
    </html>
  )
}
